### ISSUE TITLE
Website accessibility: Too many characters on one line

### ISSUE THREAD

**Issue by electrolyte-orb** [radar/joyofelixir#126]
It is advised by many UI designers (mainly by Refactoring UI by Tailwind guys) to keep the line length in check, 70-75 characters maximum on a desktop screen. Currently, it's 128 characters per line. 

All you need to do is… on the `.wrapper` element:
```css
.wrapper {
  margin: 0 auto;
  max-width: 60ch;
}
```
`ch` is the width of one character, by some hit and trial, I found that 60 is good enough, maxing at around 78 characters (including spaces).
